version: "3"
volumes:
  logs.app:
  cache.app:
services:
  nginx:
    container_name: nginx.xcart
    build:
      context: ./
      dockerfile: Dockerfile_Nginx
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/mff
      - logs.app:/app/var/logs
      - cache.app:/app/var/cache
      - ./host.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php.xcart
    build:
      context: ./
      dockerfile: Dockerfile_PHP
    links:
      - db
    volumes:
      - ./:/mff
      - logs.app:/app/var/logs
      - cache.app:/app/var/cache
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  db:
    image: mysql
    container_name: mysql.xcart
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe
    ports:
      - 3308:3308

  adminer:
    image: adminer
    container_name: adminer.xcart
    restart: always
    ports:
      - 8080:8080




