<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderItem extends \XLite\Model\OrderItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }

    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

        return parent::__isset($name);

    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'privateAttachments', 'categoryAdded', 'pinCodes', 'shippingCost', 'capostParcelItems', 'capostReturnItems', 'copyOfAmount', 'customerAttachments', 'xpaymentsSubscription', 'xpaymentsEmulated', 'xpaymentsUniqueId', 'item_id', 'object', 'name', 'sku', 'price', 'itemNetPrice', 'discountedSubtotal', 'amount', 'backorderedAmount', 'order', 'surcharges', 'dumpProduct', 'attributeValues', 'total', 'subtotal', '_previous_state'];
        }

        return ['__isInitialized__', 'privateAttachments', 'categoryAdded', 'pinCodes', 'shippingCost', 'capostParcelItems', 'capostReturnItems', 'copyOfAmount', 'customerAttachments', 'xpaymentsSubscription', 'xpaymentsEmulated', 'xpaymentsUniqueId', 'item_id', 'object', 'name', 'sku', 'price', 'itemNetPrice', 'discountedSubtotal', 'amount', 'backorderedAmount', 'order', 'surcharges', 'dumpProduct', 'attributeValues', 'total', 'subtotal', '_previous_state'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDownloadAttachments($availableOnly = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadAttachments', [$availableOnly]);

        return parent::getDownloadAttachments($availableOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function createPrivateAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createPrivateAttachments', []);

        return parent::createPrivateAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrivateAttachments(\XLite\Module\CDev\Egoods\Model\OrderItem\PrivateAttachment $privateAttachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrivateAttachments', [$privateAttachments]);

        return parent::addPrivateAttachments($privateAttachments);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivateAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivateAttachments', []);

        return parent::getPrivateAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryAdded', []);

        return parent::getCategoryAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryAdded($categoryAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryAdded', [$categoryAdded]);

        return parent::setCategoryAdded($categoryAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventCell()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventCell', []);

        return parent::getEventCell();
    }

    /**
     * {@inheritDoc}
     */
    public function isCustomerInterface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCustomerInterface', []);

        return parent::isCustomerInterface();
    }

    /**
     * {@inheritDoc}
     */
    public function countPinCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countPinCodes', []);

        return parent::countPinCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function getSoldPinCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldPinCodes', []);

        return parent::getSoldPinCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function countMissingPinCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countMissingPinCodes', []);

        return parent::countMissingPinCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function acquirePinCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'acquirePinCodes', []);

        return parent::acquirePinCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoPinCodes(\XLite\Model\Product $product, $amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoPinCodes', [$product, $amount]);

        return parent::getAutoPinCodes($product, $amount);
    }

    /**
     * {@inheritDoc}
     */
    public function salePinCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'salePinCodes', []);

        return parent::salePinCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function releasePINCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'releasePINCodes', []);

        return parent::releasePINCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function addPinCodes(\XLite\Module\CDev\PINCodes\Model\PinCode $pinCodes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPinCodes', [$pinCodes]);

        return parent::addPinCodes($pinCodes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPinCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPinCodes', []);

        return parent::getPinCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function releaseBackorder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'releaseBackorder', []);

        return parent::releaseBackorder();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCost', []);

        return parent::getShippingCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCost($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCost', [$value]);

        return parent::setShippingCost($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addCapostParcelItem(\XLite\Module\XC\CanadaPost\Model\Order\Parcel\Item $newItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCapostParcelItem', [$newItem]);

        return parent::addCapostParcelItem($newItem);
    }

    /**
     * {@inheritDoc}
     */
    public function addCapostReturnItem(\XLite\Module\XC\CanadaPost\Model\ProductsReturn\Item $newItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCapostReturnItem', [$newItem]);

        return parent::addCapostReturnItem($newItem);
    }

    /**
     * {@inheritDoc}
     */
    public function addCapostParcelItems(\XLite\Module\XC\CanadaPost\Model\Order\Parcel\Item $capostParcelItems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCapostParcelItems', [$capostParcelItems]);

        return parent::addCapostParcelItems($capostParcelItems);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapostParcelItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapostParcelItems', []);

        return parent::getCapostParcelItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addCapostReturnItems(\XLite\Module\XC\CanadaPost\Model\ProductsReturn\Item $capostReturnItems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCapostReturnItems', [$capostReturnItems]);

        return parent::addCapostReturnItems($capostReturnItems);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapostReturnItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapostReturnItems', []);

        return parent::getCapostReturnItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopyOfAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopyOfAmount', []);

        return parent::setCopyOfAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getCopyOfAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopyOfAmount', []);

        return parent::getCopyOfAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function isCustomerAttachable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCustomerAttachable', []);

        return parent::isCustomerAttachable();
    }

    /**
     * {@inheritDoc}
     */
    public function isCustomerAttachmentsRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCustomerAttachmentsRequired', []);

        return parent::isCustomerAttachmentsRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerAttachments', []);

        return parent::getCustomerAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function getKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKey', []);

        return parent::getKey();
    }

    /**
     * {@inheritDoc}
     */
    public function isConfigured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isConfigured', []);

        return parent::isConfigured();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerAttachments(\XLite\Module\XC\CustomerAttachments\Model\OrderItem\Attachment\Attachment $customerAttachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerAttachments', [$customerAttachments]);

        return parent::addCustomerAttachments($customerAttachments);
    }

    /**
     * {@inheritDoc}
     */
    public function isFreeShipping()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFreeShipping', []);

        return parent::isFreeShipping();
    }

    /**
     * {@inheritDoc}
     */
    public function isShipForFree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShipForFree', []);

        return parent::isShipForFree();
    }

    /**
     * {@inheritDoc}
     */
    public function isXpaymentsEmulated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isXpaymentsEmulated', []);

        return parent::isXpaymentsEmulated();
    }

    /**
     * {@inheritDoc}
     */
    public function isValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', []);

        return parent::isValid();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function getObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObject', []);

        return parent::getObject();
    }

    /**
     * {@inheritDoc}
     */
    public function isValidToClone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidToClone', []);

        return parent::isValidToClone();
    }

    /**
     * {@inheritDoc}
     */
    public function setXpaymentsEmulated($xpaymentsEmulated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXpaymentsEmulated', [$xpaymentsEmulated]);

        return parent::setXpaymentsEmulated($xpaymentsEmulated);
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsEmulated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsEmulated', []);

        return parent::getXpaymentsEmulated();
    }

    /**
     * {@inheritDoc}
     */
    public function getClearPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClearPrice', []);

        return parent::getClearPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function isXpaymentsSubscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isXpaymentsSubscription', []);

        return parent::isXpaymentsSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function getNetPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetPrice', []);

        return parent::getNetPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function isInitialXpaymentsSubscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInitialXpaymentsSubscription', []);

        return parent::isInitialXpaymentsSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsSetupFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsSetupFee', []);

        return parent::getXpaymentsSetupFee();
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsSubscriptionFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsSubscriptionFee', []);

        return parent::getXpaymentsSubscriptionFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setXpaymentsSubscription(\XLite\Module\XPay\XPaymentsCloud\Model\Subscription\Subscription $xpaymentsSubscription = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXpaymentsSubscription', [$xpaymentsSubscription]);

        return parent::setXpaymentsSubscription($xpaymentsSubscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsSubscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsSubscription', []);

        return parent::getXpaymentsSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsClearFeePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsClearFeePrice', []);

        return parent::getXpaymentsClearFeePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsNetFeePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsNetFeePrice', []);

        return parent::getXpaymentsNetFeePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsDisplayFeePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsDisplayFeePrice', []);

        return parent::getXpaymentsDisplayFeePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setXpaymentsUniqueId($xpaymentsUniqueId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXpaymentsUniqueId', [$xpaymentsUniqueId]);

        return parent::setXpaymentsUniqueId($xpaymentsUniqueId);
    }

    /**
     * {@inheritDoc}
     */
    public function getXpaymentsUniqueId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXpaymentsUniqueId', []);

        return parent::getXpaymentsUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    public function isXpaymentsNextPaymentDateAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isXpaymentsNextPaymentDateAvailable', []);

        return parent::isXpaymentsNextPaymentDateAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\XLite\Model\Order $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function cloneEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cloneEntity', []);

        return parent::cloneEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayPrice', []);

        return parent::getDisplayPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemPrice', []);

        return parent::getItemPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemNetPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemNetPrice', []);

        return parent::getItemNetPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function isOrderOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOrderOpen', []);

        return parent::isOrderOpen();
    }

    /**
     * {@inheritDoc}
     */
    public function getThroughExcludeSurcharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThroughExcludeSurcharges', []);

        return parent::getThroughExcludeSurcharges();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', []);

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\XLite\Model\Product $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$product]);

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function setObject(\XLite\Model\Base\IOrderItem $item = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObject', [$item]);

        return parent::setObject($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmountWarning($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmountWarning', [$amount]);

        return parent::getAmountWarning($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackorderedAmount($backorderedAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackorderedAmount', [$backorderedAmount]);

        return parent::setBackorderedAmount($backorderedAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function processAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'processAmount', [$amount]);

        return parent::processAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', []);

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getClearWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClearWeight', []);

        return parent::getClearWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function hasImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasImage', []);

        return parent::hasImage();
    }

    /**
     * {@inheritDoc}
     */
    public function hasWrongAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasWrongAmount', []);

        return parent::hasWrongAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageURL', []);

        return parent::getImageURL();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageRelativeURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageRelativeURL', []);

        return parent::getImageRelativeURL();
    }

    /**
     * {@inheritDoc}
     */
    public function getResizedImageURL($width, $height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResizedImageURL', [$width, $height]);

        return parent::getResizedImageURL($width, $height);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getMiniCartImageWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiniCartImageWidth', []);

        return parent::getMiniCartImageWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getMiniCartImageHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiniCartImageHeight', []);

        return parent::getMiniCartImageHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtendedDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtendedDescription', []);

        return parent::getExtendedDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductAvailableAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductAvailableAmount', []);

        return parent::getProductAvailableAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getURL', []);

        return parent::getURL();
    }

    /**
     * {@inheritDoc}
     */
    public function isShippable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShippable', []);

        return parent::isShippable();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValuesIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValuesIds', []);

        return parent::getAttributeValuesIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValuesPlain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValuesPlain', []);

        return parent::getAttributeValuesPlain();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValuesAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValuesAsString', []);

        return parent::getAttributeValuesAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValuesCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValuesCount', []);

        return parent::getAttributeValuesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getSortedAttributeValues($limit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortedAttributeValues', [$limit]);

        return parent::getSortedAttributeValues($limit);
    }

    /**
     * {@inheritDoc}
     */
    public function canChangeAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canChangeAmount', []);

        return parent::canChangeAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function isValidAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidAmount', []);

        return parent::isValidAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function isActualAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActualAttributes', []);

        return parent::isActualAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeValues(array $attributeValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeValues', [$attributeValues]);

        return parent::setAttributeValues($attributeValues);
    }

    /**
     * {@inheritDoc}
     */
    public function hasAttributeValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAttributeValues', []);

        return parent::hasAttributeValues();
    }

    /**
     * {@inheritDoc}
     */
    public function calculate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculate', []);

        return parent::calculate();
    }

    /**
     * {@inheritDoc}
     */
    public function renew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'renew', []);

        return parent::renew();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxable', []);

        return parent::getTaxable();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxableBasis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxableBasis', []);

        return parent::getTaxableBasis();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductClass', []);

        return parent::getProductClass();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateTotal', []);

        return parent::calculateTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayTotal', []);

        return parent::getDisplayTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateNetSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateNetSubtotal', []);

        return parent::calculateNetSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getNetSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetSubtotal', []);

        return parent::getNetSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getInventoryAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventoryAmount', []);

        return parent::getInventoryAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function changeAmount($delta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changeAmount', [$delta]);

        return parent::changeAmount($delta);
    }

    /**
     * {@inheritDoc}
     */
    public function isPriceControlledServer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPriceControlledServer', []);

        return parent::isPriceControlledServer();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemId', []);

        return parent::getItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setSku($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', [$sku]);

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', []);

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemNetPrice($itemNetPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemNetPrice', [$itemNetPrice]);

        return parent::setItemNetPrice($itemNetPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountedSubtotal($discountedSubtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountedSubtotal', [$discountedSubtotal]);

        return parent::setDiscountedSubtotal($discountedSubtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountedSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountedSubtotal', []);

        return parent::getDiscountedSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getBackorderedAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackorderedAmount', []);

        return parent::getBackorderedAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', []);

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function addSurcharges(\XLite\Model\OrderItem\Surcharge $surcharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSurcharges', [$surcharges]);

        return parent::addSurcharges($surcharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurcharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurcharges', []);

        return parent::getSurcharges();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttributeValues(\XLite\Model\OrderItem\AttributeValue $attributeValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttributeValues', [$attributeValues]);

        return parent::addAttributeValues($attributeValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValues', []);

        return parent::getAttributeValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', [$subtotal]);

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcludeSurcharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcludeSurcharges', []);

        return parent::getExcludeSurcharges();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncludeSurcharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncludeSurcharges', []);

        return parent::getIncludeSurcharges();
    }

    /**
     * {@inheritDoc}
     */
    public function getExcludeSurchargesByType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcludeSurchargesByType', [$type]);

        return parent::getExcludeSurchargesByType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurchargeTotals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurchargeTotals', []);

        return parent::getSurchargeTotals();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleteSurchargeTotals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleteSurchargeTotals', []);

        return parent::getCompleteSurchargeTotals();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateSurchargeTotals($surcharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateSurchargeTotals', [$surcharges]);

        return parent::calculateSurchargeTotals($surcharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurchargeSum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurchargeSum', []);

        return parent::getSurchargeSum();
    }

    /**
     * {@inheritDoc}
     */
    public function getSurchargeSumByType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurchargeSumByType', [$type]);

        return parent::getSurchargeSumByType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurchargeTotalByType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurchargeTotalByType', [$type]);

        return parent::getSurchargeTotalByType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function resetSurcharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetSurcharges', []);

        return parent::resetSurcharges();
    }

    /**
     * {@inheritDoc}
     */
    public function resetSurcharge($surcharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetSurcharge', [$surcharge]);

        return parent::resetSurcharge($surcharge);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSurcharge($surcharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSurcharge', [$surcharge]);

        return parent::removeSurcharge($surcharge);
    }

    /**
     * {@inheritDoc}
     */
    public function compareSurcharges(array $oldSurcharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'compareSurcharges', [$oldSurcharges]);

        return parent::compareSurcharges($oldSurcharges);
    }

    /**
     * {@inheritDoc}
     */
    public function buildDataForREST($withAssociations = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'buildDataForREST', [$withAssociations]);

        return parent::buildDataForREST($withAssociations);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelAssociationsForREST()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelAssociationsForREST', []);

        return parent::getModelAssociationsForREST();
    }

    /**
     * {@inheritDoc}
     */
    public function _getPreviousState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_getPreviousState', []);

        return parent::_getPreviousState();
    }

    /**
     * {@inheritDoc}
     */
    public function map(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'map', [$data]);

        return parent::map($data);
    }

    /**
     * {@inheritDoc}
     */
    public function __unset($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unset', [$name]);

        return parent::__unset($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', []);

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function checkCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkCache', []);

        return parent::checkCache();
    }

    /**
     * {@inheritDoc}
     */
    public function detach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'detach', []);

        return parent::detach();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, array $args = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $args]);

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function isPropertyExists($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPropertyExists', [$name]);

        return parent::isPropertyExists($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setterProperty($property, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setterProperty', [$property, $value]);

        return parent::setterProperty($property, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getterProperty($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getterProperty', [$property]);

        return parent::getterProperty($property);
    }

    /**
     * {@inheritDoc}
     */
    public function isPersistent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPersistent', []);

        return parent::isPersistent();
    }

    /**
     * {@inheritDoc}
     */
    public function isDetached()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDetached', []);

        return parent::isDetached();
    }

    /**
     * {@inheritDoc}
     */
    public function isManaged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isManaged', []);

        return parent::isManaged();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifierName', []);

        return parent::getUniqueIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifier', []);

        return parent::getUniqueIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityName', []);

        return parent::getEntityName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldMetadata($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldMetadata', [$property]);

        return parent::getFieldMetadata($property);
    }

    /**
     * {@inheritDoc}
     */
    public function update()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', []);

        return parent::update();
    }

    /**
     * {@inheritDoc}
     */
    public function create()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'create', []);

        return parent::create();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function processFiles($field, array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'processFiles', [$field, $data]);

        return parent::processFiles($field, $data);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldsDefinition($class = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldsDefinition', [$class]);

        return parent::getFieldsDefinition($class);
    }

    /**
     * {@inheritDoc}
     */
    public function prepareEntityBeforeCommit($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareEntityBeforeCommit', [$type]);

        return parent::prepareEntityBeforeCommit($type);
    }

    /**
     * {@inheritDoc}
     */
    public function isSerializable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSerializable', []);

        return parent::isSerializable();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
